services:
  - type: web
    name: log20-disponibilidade-frota
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
